steps:
  - name: node:20.11.1
    entrypoint: npm
    args: ["install"]
  - name: node:20.11.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
    - 'NEXTAUTH_SECRET=a_secret_key'
    - 'NEXTAUTH_URL=https://my-next-app-dot-challengelatam-406716.ue.r.appspot.com/'
    - 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
    - 'GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}'
  - name: node:20.11.1
    entrypoint: npm
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    timeout: "1600s"
