steps:
  - name: node:20.11.1
    entrypoint: npm
    args: ["install"]
  - name: node:20.11.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - 'GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}'
      - 'GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}'
  - name: node:20.11.1
    entrypoint: npm
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    timeout: "1600s"
